# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 127d6d37ff333a0f4e5b245e5b0378b268ee951e5bc2cdb871f306860fa7e357e2207d22ad8f1aa929f29a35a624615f4d6558f3d211f30af1bd4ab1542e53e3

test:
  secret_key_base: c808eb6bae5d5698fd94f2545eae4a6d3288c81ffe9bdc779386f35b67b4ba12d89aeb909ec653eda7bcdee32a18981b2bb45241ffd0647316e202f861f1e8dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
